import { readFileSync } from 'node:fs';
import { extname } from 'node:path';
import { toPosixRelative, walkFiles } from '../application/file-walker.js';
import type { DiscoveredProject } from '../application/model.js';

const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.mts', '.cts', '.js', '.jsx', '.mjs', '.cjs']);
const TYPESCRIPT_EXTENSIONS = new Set(['.ts', '.tsx', '.mts', '.cts']);
const TEST_FILE = /\.(spec|test|cy)\.[cm]?[jt]sx?$/i;
const TEST_DIRECTORY = /(^|\/)(cypress|e2e|__tests__)\//i;
const GENERATED_FILE = /(\.generated\.[cm]?[jt]sx?|\.g\.ts|\.min\.js)$/i;
const GENERATED_HEADER = /<auto-generated|@generated/i;
const HEADER_BYTES = 512;

/** One source file that will be analyzed, and who owns it. */
export interface OwnedFile {
  path: string;
  project: DiscoveredProject;
  /** Module path relative to the owning project's root, without extension (e.g. `src/app/app`). */
  modulePath: string;
  language: 'typescript' | 'javascript';
}

export interface ProjectFileSet {
  analyzed: OwnedFile[];
  ignored: number;
}

export function isSourceFileName(name: string): boolean {
  return SOURCE_EXTENSIONS.has(extname(name).toLowerCase()) && !/\.d\.[cm]?ts$/i.test(name);
}

export function languageOf(path: string): 'typescript' | 'javascript' {
  return TYPESCRIPT_EXTENSIONS.has(extname(path).toLowerCase()) ? 'typescript' : 'javascript';
}

/** Path relative to `root`, without the source extension (`.d.ts` included). */
export function modulePathOf(root: string, path: string): string {
  return toPosixRelative(root, path).replace(/(\.d)?\.[cm]?[jt]sx?$/i, '');
}

/**
 * Lists a project's files: sources under its `sourceRoot` (minus nested projects), skipping
 * tests (unless `includeTests`) and generated code, both of which are counted as ignored.
 */
export function listProjectFiles(project: DiscoveredProject, includeTests: boolean): ProjectFileSet {
  const candidates = walkFiles(project.sourceRoot, isSourceFileName, project.excludedDirs);
  const analyzed: OwnedFile[] = [];
  let ignored = 0;

  for (const path of candidates) {
    const relative = toPosixRelative(project.sourceRoot, path);
    const isTest = TEST_FILE.test(path) || TEST_DIRECTORY.test(`${relative}`);
    if ((isTest && !includeTests) || isGenerated(path)) {
      ignored++;
      continue;
    }
    analyzed.push({
      path,
      project,
      modulePath: modulePathOf(project.rootDir, path),
      language: languageOf(path),
    });
  }

  return { analyzed, ignored };
}

function isGenerated(path: string): boolean {
  if (GENERATED_FILE.test(path)) {
    return true;
  }
  try {
    return GENERATED_HEADER.test(readFileSync(path, 'utf8').slice(0, HEADER_BYTES));
  } catch {
    return false;
  }
}
